version: "3.3"

services:
  mynds:
    build: .
    labels:
      - "holten.publish=j"
      - "traefik.http.routers.mynds.tls=true"
      - "traefik.http.routers.mynds.tls.certresolver=letsencrypt"
    networks:
      - traefik

networks:
  traefik:
     external: true
