version: '3'

services:
    traefik:
        image: traefik:v2.8
        ports:
            - "80:80"
            - "443:443"
        restart: unless-stopped
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./traefik.yml:/traefik.yml
            - "./nextcloud_fileprovider+certs.yml:/nextcloud_fileprovider+certs.yml"
            - ./traefik_security_settings.yml:/traefik_security_settings.yml
            - ./acme.json:/acme.json
            - /etc/letsencrypt:/etc/letsencrypt
        labels:
            - "holten.publish=vpn"
            - "traefik.http.routers.traefik.tls=true"
            - "traefik.http.routers.traefik.service=api@internal"
            - "traefik.http.routers.traefik.middlewares=whitelistvpn@file,admin-basicauth@file"

        networks:
            - traefik
networks:
    traefik:
        external: true
