import { Open_Sans } from "next/font/google";
import "./globals.css";

const font = Open_Sans({
  style: ['normal', 'italic'],
  weight: ['400', '700', '800'],
  subsets: ["latin"],
});

export const metadata = {
  title: "Mynds",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={font.className}>{children}</body>
    </html>
  );
}
